function SignalAnalysisLauncher()
% SignalAnalysisLauncher - 信号分析工具箱入口
%
% 替代 main.m。弹出工具选择面板。

    % 确保当前目录及子目录在路径中
    thisDir = fileparts(mfilename('fullpath'));
    addpath(thisDir);
    addpath(fullfile(thisDir, 'core'));
    rehash;  % 刷新类缓存

    fig = figure( ...
        'Name', 'Signal Analysis Toolbox', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'Position', [400 300 350 200], ...
        'Resize', 'off');

    % 标题
    uicontrol(fig, 'Style', 'text', ...
        'String', 'Signal Analysis Toolbox v2.0', ...
        'FontSize', 14, 'FontWeight', 'bold', ...
        'Units', 'normalized', ...
        'Position', [0.1 0.75 0.8 0.2]);

    % 时域分析按钮
    uicontrol(fig, 'Style', 'pushbutton', ...
        'String', 'Time Series Analysis', ...
        'FontSize', 12, ...
        'Units', 'normalized', ...
        'Position', [0.2 0.5 0.6 0.15], ...
        'Callback', @(~,~) LaunchTimeSeries(fig));

    % 传函分析按钮
    uicontrol(fig, 'Style', 'pushbutton', ...
        'String', 'Transfer Function Analysis', ...
        'FontSize', 12, ...
        'Units', 'normalized', ...
        'Position', [0.2 0.3 0.6 0.15], ...
        'Callback', @(~,~) LaunchTransferFunction(fig));
end

function LaunchTimeSeries(fig)
    try
        delete(fig);
        ts = TimeSeriesAnalyzer(); %#ok<NASGU>
    catch e
        errordlg(sprintf('启动时域分析失败:\n%s\n\n%s', e.message, e.getReport()), 'Error');
    end
end

function LaunchTransferFunction(fig)
    try
        delete(fig);
        tf = TransferFunctionAnalyzer(); %#ok<NASGU>
    catch e
        errordlg(sprintf('启动传函分析失败:\n%s\n\n%s', e.message, e.getReport()), 'Error');
    end
end
